spring:
  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: always
      data-locations:
        classpath: data.sql
      schema-locations:
        classpath: schema.sql
  h2:
    console:
      enabled: true