spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: main
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local
